name = "CTNH"
author = "Analytic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d30f8215d955634730806ea090fe1fa03fcf5a01ece5c736b76d0f1157e22731"

[versions]
forge = "47.4.1"
minecraft = "1.20.1"
