name = "CTNH"
author = "Analytic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee61f552b530c3ed57a1e0d9afecde870d4c3dc16e8afda2ae279d53171685c4"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
